// 翻訳データ
const menuTranslations = {
    "jp": {
        // --- サイト全体（キャッチコピー刷新） ---
        "catchphrase": "那覇、若狭。<br>心ほどける、<br>大人の隠れ家。",
        "sub-catchphrase": "厳選した泡盛と、炭火香る絶品料理。<br>今夜は時間を忘れて、語り合いませんか。",
        
        "about-title": "かふーじゅの想い",
        "about-body-1": "店名である「かふーじゅ」は、沖縄の言葉で「果報（かふう）」、つまり「幸せ」や「良い知らせ」を意味します。",
        "about-body-2": "私たちが目指すのは、訪れるたびに心が温まり、明日への活力が湧いてくるような場所。<br>こだわりの酒と肴、そして何より「人」との繋がりを大切にしています。",
        "about-body-3": "この若狭の地で、皆様の日常に小さな「果報」をお届けできるよう、今夜も明かりを灯してお待ちしております。",
        
        "info-title": "店舗情報・地図",
        "menu-title": "お品書き",
        "events-title": "催し物",
        "contact-title": "ご予約・お問い合わせ",
        "contact-reserve-title": "ご予約方法",
        "contact-reserve-desc": "お席のご予約は、お電話またはInstagramのDMにて承っております。<br>週末や8名様以上の団体利用は、お早めのご連絡をおすすめいたします。",
        "contact-form-title": "お問い合わせ",
        "form-name": "お名前",
        "form-email": "メールアドレス",
        "form-message": "ご用件",
        "form-submit": "送信する",
        
        // --- イベント ---
        "event-1-title": "【11月限定】和牛リブロース半額",
        "event-1-date": "開催期間：11月25日(土)〜30日(木)",
        "event-1-desc": "日頃の感謝を込めて、A5ランク和牛リブロースステーキ(通常2,480円)を、半額の1,240円でご提供いたします。数量限定のため、売り切れの際はご容赦ください。",
        "event-2-title": "月曜日はビールDay",
        "event-2-desc": "週の始まりを元気に。生ビール何杯飲んでも1杯300円！",
        "event-3-title": "水曜レディースDay",
        "event-3-desc": "女性グループのお客様限定で、本日のデザートをサービス。",
        "event-4-title": "毎月29日は肉の日",
        "event-4-desc": "ステーキ、ハンバーグなど対象の肉料理が全品10%OFF。",
        
        // --- カテゴリ ---
        "tab-food": "お料理",
        "tab-drink": "お飲み物",
        "cat-otsumami": "とりあえず・肴",
        "cat-agemono": "揚げ物",
        "cat-ippinmono": "一品料理",
        "cat-niku": "肉料理",
        "cat-main": "ご飯・麺",
        "cat-dessert": "甘味",
        "cat-alcohol": "アルコール",
        "cat-nonalcohol": "ノンアルコール",
        "modal-allergens-title": "含まれるアレルゲン",

        // --- メニューアイテム (名前も少し美味しそうに修正) ---
        "iburigakko": "いぶりがっこチーズ",
        "iburigakko-desc": "秋田名物の燻製漬物とクリームチーズ。酒泥棒な一品。",
        "shutou-cheese": "酒盗クリームチーズ",
        "shutou-cheese-desc": "カツオの酒盗の塩気とチーズのまろやかさが絶妙。",
        "yamaimo-zakuzaku": "山芋ザクザク",
        "yamaimo-zakuzaku-desc": "新鮮な山芋を特製ダレで。食感が楽しいスピードメニュー。",
        "mozukusu": "沖縄県産 もずく酢",
        "mozukusu-desc": "太くてコシのある沖縄もずくを、さっぱり三杯酢で。",
        "umibudou": "海ぶどう",
        "umibudou-desc": "プチプチ食感がたまらない、沖縄の海の宝石。",
        "kyuri-ippon": "きゅうり一本漬け",
        "kyuri-ippon-desc": "箸休めに最適。出汁の効いた浅漬け。",
        "hiyayakko": "薬味たっぷり冷や奴",
        "hiyayakko-desc": "ネギ、生姜、かつお節をどっさりと乗せました。",
        "caesar-salad": "厚切りベーコンのシーザーサラダ",
        "caesar-salad-desc": "濃厚ドレッシングと温泉卵を絡めてどうぞ。",
        "pirikara-tamago": "特製ピリ辛半熟玉子",
        "pirikara-tamago-desc": "とろ〜り半熟。秘伝のピリ辛ダレに漬け込みました。",
        "pirikara-menma": "ピリ辛おつまみメンマ",
        "pirikara-menma-desc": "ごま油の香りが食欲をそそる、ビールのお供。",
        "aburi-charshu": "自家製 炙りチャーシュー",
        "aburi-charshu-desc": "じっくり煮込んだ豚バラを、提供直前に香ばしく炙ります。",
        "wakadori-karaage": "秘伝だれ 若鶏からあげ",
        "wakadori-karaage-desc": "肉汁溢れるジューシーな仕上がり。当店一番人気。",
        "potato-fry": "皮付きポテトフライ",
        "potato-fry-desc": "ホクホク感が楽しめる皮付きタイプ。",
        "atsuage-yakumi": "カリカリ厚揚げ 薬味まみれ",
        "atsuage-yakumi-desc": "外はカリッと中はふわふわ。生姜醤油で。",
        "youngcorn-tenpura": "ヤングコーンの天ぷら",
        "youngcorn-tenpura-desc": "ヒゲまで美味しい。素材の甘みを塩で。",
        "tacos-meatpie": "自家製タコスミートパイ",
        "tacos-meatpie-desc": "サクサクのパイ生地にスパイシーなタコスミート。",
        "taimo-cheese": "田芋（ターンム）チーズ焼き",
        "taimo-cheese-desc": "沖縄の祝い芋「田芋」の甘みとチーズの塩気が相性抜群。",
        "mabo-dofu": "四川風 麻婆豆腐",
        "mabo-dofu-desc": "花椒の痺れと辛さが癖になる、本格派。",
        "anchovy-cabbage": "アンチョビキャベツ",
        "anchovy-cabbage-desc": "ニンニクとアンチョビの香りで、ハイボールが進みます。",
        "gyoza": "手包み 肉汁餃子（5個）",
        "gyoza-desc": "噛むと肉汁が飛び出します。火傷にご注意ください。",
        "tofu-garlic": "スタミナ豆腐ニンニク",
        "tofu-garlic-desc": "ガツンとニンニクを効かせた、活力の出る一皿。",
        "goya-chanpuru": "ゴーヤーチャンプルー",
        "goya-chanpuru-desc": "沖縄料理の王道。苦味を抑えて食べやすく仕上げました。",
        "dashimaki": "出汁香る だし巻き卵",
        "dashimaki-desc": "ご注文を受けてから一本一本丁寧に焼き上げます。",
        "niku-yakimochi": "肉巻き焼きもち",
        "niku-yakimochi-desc": "甘辛い肉ダレと、餅のもちもち食感がたまりません。",
        "gyu-rare-katsu": "黒毛和牛のレアカツ",
        "gyu-rare-katsu-desc": "サクッとした衣と、とろける赤身のレア加減。",
        "rib-steak": "リブロースステーキ",
        "rib-steak-desc": "肉の旨味をダイレクトに味わう、ボリューム満点の一皿。",
        "wagyu-rib-steak": "A5和牛リブロースステーキ",
        "wagyu-rib-steak-desc": "特別な夜に。口の中で脂が甘く溶け出します。",
        "hamburger": "特製 粗挽きハンバーグ",
        "hamburger-desc": "肉肉しさを残した粗挽きパティ。デミグラスソースで。",
        "chicken-tatsuta": "若鶏の竜田揚げ",
        "chicken-tatsuta-desc": "生姜醤油に漬け込んだ、サクサク食感の竜田揚げ。",
        "chicken-steak": "チキンステーキ ガーリックソース",
        "chicken-steak-desc": "皮面をパリパリに焼き上げました。",
        "reimen": "〆の特製冷麺",
        "reimen-desc": "魚介出汁の効いた透き通るスープでさっぱりと。",
        "garlic-pizza": "ガーリックミートピザ",
        "garlic-pizza-desc": "薄焼きクリスピー生地。おつまみ感覚で食べられるピザ。",
        "margherita": "王道マルゲリータ",
        "margherita-desc": "トマトとバジルのシンプルな美味しさ。",
        "koumi-chahan": "香味野菜のチャーハン",
        "koumi-chahan-desc": "大葉やミョウガなどの香味野菜が香る、大人のチャーハン。",
        "mayu-chahan": "黒マー油チャーハン",
        "mayu-chahan-desc": "焦がしニンニク油の香ばしさが食欲をそそります。",
        "taco-rice": "〆のミニタコライス",
        "taco-rice-desc": "少しだけ食べたい時に丁度いいサイズ。",
        "vanilla-ice": "濃厚バニラアイス",
        "vanilla-ice-desc": "バニラビーンズたっぷり。",
        "age-mochi": "揚げ餅 黒蜜きなこ",
        "age-mochi-desc": "熱々の揚げ餅に、冷たいアイスを添えても美味しい。",
        "beer": "オリオン ザ・ドラフト",
        "beer-desc": "沖縄の定番。キンキンに冷えてます。",
        "awamori": "泡盛 各種",
        "awamori-desc": "残波、菊之露、各種古酒を取り揃えております。",
        "sanpincha": "さんぴん茶",
        "sanpincha-desc": "沖縄料理にはやっぱりこれ。"
    },
    "en": {
        "catchphrase": "Naha, Wakasa.<br>Your Heart's<br>Hideaway.",
        "sub-catchphrase": "Exquisite charcoal-grilled dishes & Awamori.<br>Forget time and unwind tonight.",
        "about-title": "Our Philosophy",
        "about-body-1": "'Kafuju' means 'good fortune' or 'happiness' in the Okinawan dialect.",
        "about-body-2": "We aim to be a place where you can relax and recharge.<br>We cherish the connection between people, good sake, and good food.",
        "about-body-3": "We are waiting for you tonight in Wakasa, hoping to bring a little happiness to your day.",
        "info-title": "Info & Access",
        "menu-title": "Menu",
        "events-title": "Events",
        "contact-title": "Reservations",
        "contact-reserve-title": "Reservations",
        "contact-reserve-desc": "Reservations can be made via Phone or Instagram DM.<br>Please contact us in advance for groups of 8 or more.",
        "contact-form-title": "Inquiry",
        "form-name": "Name",
        "form-email": "Email",
        "form-message": "Message",
        "form-submit": "Send",
        
        "event-1-title": "Wagyu Steak Half Price",
        "event-1-date": "Nov 25 (Sat) - 30 (Thu)",
        "event-1-desc": "A5 Rank Wagyu Ribeye Steak at half price! Limited quantity available.",
        "event-2-title": "Beer Day (Mon)",
        "event-2-desc": "All draft beers ¥300 on Mondays!",
        "event-3-title": "Ladies' Day (Wed)",
        "event-3-desc": "Free dessert for female groups on Wednesdays.",
        "event-4-title": "Meat Day (29th)",
        "event-4-desc": "10% OFF on selected meat dishes on the 29th of every month.",
        
        "tab-food": "Food",
        "tab-drink": "Drinks",
        "cat-otsumami": "Appetizers",
        "cat-agemono": "Fried",
        "cat-ippinmono": "Dishes",
        "cat-niku": "Meat",
        "cat-main": "Rice/Noodle",
        "cat-dessert": "Dessert",
        "cat-alcohol": "Alcohol",
        "cat-nonalcohol": "Non-Alcoholic",
        "modal-allergens-title": "Allergens",

        "iburigakko": "Smoked Radish & Cheese",
        "iburigakko-desc": "Smoked pickled radish paired with cream cheese.",
        "shutou-cheese": "Salted Bonito & Cheese",
        "shutou-cheese-desc": "Fermented bonito entrails with cream cheese. Great with Sake.",
        "yamaimo-zakuzaku": "Crunchy Yam",
        "yamaimo-zakuzaku-desc": "Fresh mountain yam with special sauce.",
        "mozukusu": "Mozuku Vinegar",
        "mozukusu-desc": "Okinawan seaweed in vinegar.",
        "umibudou": "Sea Grapes",
        "umibudou-desc": "Seaweed with a unique popping texture.",
        "kyuri-ippon": "Pickled Cucumber",
        "kyuri-ippon-desc": "Whole cucumber lightly pickled.",
        "hiyayakko": "Chilled Tofu",
        "hiyayakko-desc": "Topped with ginger, green onions, and bonito flakes.",
        "caesar-salad": "Caesar Salad",
        "caesar-salad-desc": "With thick-cut bacon and soft-boiled egg.",
        "pirikara-tamago": "Spicy Egg",
        "pirikara-tamago-desc": "Soft-boiled egg marinated in spicy sauce.",
        "pirikara-menma": "Spicy Bamboo Shoots",
        "pirikara-menma-desc": "Seasoned with sesame oil.",
        "aburi-charshu": "Seared Pork",
        "aburi-charshu-desc": "Homemade roast pork, seared before serving.",
        "wakadori-karaage": "Fried Chicken",
        "wakadori-karaage-desc": "Juicy Japanese style fried chicken.",
        "potato-fry": "French Fries",
        "potato-fry-desc": "Crispy skin-on potato wedges.",
        "atsuage-yakumi": "Fried Tofu",
        "atsuage-yakumi-desc": "Crispy deep-fried tofu with herbs.",
        "youngcorn-tenpura": "Baby Corn Tempura",
        "youngcorn-tenpura-desc": "Sweet baby corn fried in light batter.",
        "tacos-meatpie": "Taco Meat Pie",
        "tacos-meatpie-desc": "Crispy pie filled with spicy taco meat.",
        "taimo-cheese": "Taro & Cheese",
        "taimo-cheese-desc": "Okinawan taro baked with cheese.",
        "mabo-dofu": "Mapo Tofu",
        "mabo-dofu-desc": "Sichuan style spicy tofu.",
        "anchovy-cabbage": "Anchovy Cabbage",
        "anchovy-cabbage-desc": "Stir-fried with garlic and anchovies.",
        "gyoza": "Gyoza (5pcs)",
        "gyoza-desc": "Juicy pork dumplings.",
        "tofu-garlic": "Garlic Tofu",
        "tofu-garlic-desc": "Stir-fried tofu with garlic punch.",
        "goya-chanpuru": "Goya Chanpuru",
        "goya-chanpuru-desc": "Classic Okinawan bitter melon stir-fry.",
        "dashimaki": "Rolled Omelet",
        "dashimaki-desc": "Fluffy Japanese omelet with dashi stock.",
        "niku-yakimochi": "Meat Wrapped Mochi",
        "niku-yakimochi-desc": "Rice cake wrapped in pork with sweet soy sauce.",
        "gyu-rare-katsu": "Rare Beef Cutlet",
        "gyu-rare-katsu-desc": "Crispy outside, rare inside.",
        "rib-steak": "Ribeye Steak",
        "rib-steak-desc": "Hearty and flavorful steak.",
        "wagyu-rib-steak": "Wagyu Ribeye Steak",
        "wagyu-rib-steak-desc": "A5 Rank Wagyu. Melt-in-your-mouth.",
        "hamburger": "Hamburger Steak",
        "hamburger-desc": "Juicy patty with demi-glace sauce.",
        "chicken-tatsuta": "Chicken Tatsuta",
        "chicken-tatsuta-desc": "Crispy fried chicken with ginger soy flavor.",
        "chicken-steak": "Chicken Steak",
        "chicken-steak-desc": "Crispy skin with garlic sauce.",
        "reimen": "Cold Noodles",
        "reimen-desc": "Refreshing seafood broth soup.",
        "garlic-pizza": "Garlic Meat Pizza",
        "garlic-pizza-desc": "Crispy pizza perfect for drinking.",
        "margherita": "Margherita",
        "margherita-desc": "Tomato, basil, and cheese.",
        "koumi-chahan": "Aromatic Fried Rice",
        "koumi-chahan-desc": "Fried rice with aromatic herbs.",
        "mayu-chahan": "Black Garlic Rice",
        "mayu-chahan-desc": "Fried rice with burnt garlic oil.",
        "taco-rice": "Mini Taco Rice",
        "taco-rice-desc": "Okinawan soul food in mini size.",
        "vanilla-ice": "Vanilla Ice Cream",
        "vanilla-ice-desc": "Rich vanilla flavor.",
        "age-mochi": "Fried Mochi",
        "age-mochi-desc": "With brown sugar syrup and soy powder.",
        "beer": "Draft Beer",
        "beer-desc": "Orion Draft Beer.",
        "awamori": "Awamori",
        "awamori-desc": "Various Okinawan spirits available.",
        "sanpincha": "Jasmine Tea",
        "sanpincha-desc": "Okinawan jasmine tea."
    },
    "cn": {
        "catchphrase": "那霸，若狭。<br>心灵的<br>避风港。",
        "sub-catchphrase": "严选泡盛与炭火绝品料理。<br>今晚忘却时间，尽情畅谈。",
        "about-title": "我们的理念",
        "about-body-1": "店名“Kafuju”在冲绳方言中意为“好运”或“幸福”。",
        "about-body-2": "我们致力于打造一个温暖人心、充满活力的地方。<br>珍惜美酒、佳肴，以及人与人之间的羁绊。",
        "about-body-3": "我们在若狭这片土地上，点亮灯火，期待为您带来小小的“幸福”。",
        "info-title": "店铺信息",
        "menu-title": "菜单",
        "events-title": "活动",
        "contact-title": "预约 / 咨询",
        "contact-reserve-title": "预约方法",
        "contact-reserve-desc": "请通过电话或Instagram私信预约。<br>8人以上团体请提前联系。",
        "contact-form-title": "咨询",
        "form-name": "姓名",
        "form-email": "邮箱",
        "form-message": "内容",
        "form-submit": "发送",
        
        "event-1-title": "和牛牛排半价",
        "event-1-date": "11月25日 (周六) 〜",
        "event-1-desc": "A5级和牛肋眼牛排半价优惠！数量有限！",
        "event-2-title": "啤酒日 (周一)",
        "event-2-desc": "生啤酒每杯300日元！",
        "event-3-title": "女士日 (周三)",
        "event-3-desc": "女性团体赠送甜点！",
        "event-4-title": "肉之日 (29日)",
        "event-4-desc": "肉类菜品9折优惠！",
        
        "tab-food": "料理",
        "tab-drink": "饮料",
        "cat-otsumami": "前菜",
        "cat-agemono": "炸物",
        "cat-ippinmono": "一品料理",
        "cat-niku": "肉类",
        "cat-main": "主食",
        "cat-dessert": "甜点",
        "cat-alcohol": "酒类",
        "cat-nonalcohol": "无酒精",
        "modal-allergens-title": "过敏原",

        "iburigakko": "烟熏萝卜奶酪",
        "iburigakko-desc": "烟熏萝卜配奶油奶酪。",
        "shutou-cheese": "酒盗奶油芝士",
        "shutou-cheese-desc": "腌制鲣鱼内脏配芝士。绝配清酒。",
        "yamaimo-zakuzaku": "香脆山药",
        "yamaimo-zakuzaku-desc": "新鲜山药配特制酱汁。",
        "mozukusu": "醋拌水云",
        "mozukusu-desc": "冲绳特产海藻。",
        "umibudou": "海葡萄",
        "umibudou-desc": "口感独特的“绿色鱼子酱”。",
        "kyuri-ippon": "腌黄瓜",
        "kyuri-ippon-desc": "清爽的一整根黄瓜。",
        "hiyayakko": "日式冷豆腐",
        "hiyayakko-desc": "配姜末、葱花和木鱼花。",
        "caesar-salad": "凯撒沙拉",
        "caesar-salad-desc": "厚切培根与温泉蛋。",
        "pirikara-tamago": "特制香辣半熟蛋",
        "pirikara-tamago-desc": "腌制在特制辣酱中。",
        "pirikara-menma": "香辣笋干",
        "pirikara-menma-desc": "芝麻油风味。",
        "aburi-charshu": "炙烤叉烧",
        "aburi-charshu-desc": "上桌前炙烤的自制叉烧。",
        "wakadori-karaage": "日式炸鸡块",
        "wakadori-karaage-desc": "鲜嫩多汁，人气第一。",
        "potato-fry": "带皮炸薯条",
        "potato-fry-desc": "热腾腾的美味。",
        "atsuage-yakumi": "佐料满满炸豆腐",
        "atsuage-yakumi-desc": "外酥里嫩。",
        "youngcorn-tenpura": "玉米笋天妇罗",
        "youngcorn-tenpura-desc": "品尝素材的甘甜。",
        "tacos-meatpie": "塔可肉派",
        "tacos-meatpie-desc": "酥皮配香辣塔可肉酱。",
        "taimo-cheese": "焗烤田芋芝士",
        "taimo-cheese-desc": "冲绳田芋与芝士的完美结合。",
        "mabo-dofu": "麻婆豆腐",
        "mabo-dofu-desc": "正宗四川风味。",
        "anchovy-cabbage": "凤尾鱼炒卷心菜",
        "anchovy-cabbage-desc": "大蒜和凤尾鱼的咸香。",
        "gyoza": "肉汁煎饺",
        "gyoza-desc": "小心肉汁烫口。",
        "tofu-garlic": "大蒜炒豆腐",
        "tofu-garlic-desc": "蒜香浓郁，补充体力。",
        "goya-chanpuru": "苦瓜炒什锦",
        "goya-chanpuru-desc": "冲绳的灵魂料理。",
        "dashimaki": "高汤鸡蛋卷",
        "dashimaki-desc": "现点现做，口感松软。",
        "niku-yakimochi": "肉卷烤年糕",
        "niku-yakimochi-desc": "甜咸酱汁配Q弹年糕。",
        "gyu-rare-katsu": "炸半熟牛排",
        "gyu-rare-katsu-desc": "外酥里嫩的半熟口感。",
        "rib-steak": "肋眼牛排",
        "rib-steak-desc": "分量十足，肉香四溢。",
        "wagyu-rib-steak": "和牛肋眼牛排",
        "wagyu-rib-steak-desc": "A5等级和牛，入口即化。",
        "hamburger": "特制汉堡肉饼",
        "hamburger-desc": "粗挽肉馅，肉感十足。",
        "chicken-tatsuta": "龙田风炸鸡",
        "chicken-tatsuta-desc": "姜酱油风味。",
        "chicken-steak": "香煎鸡排",
        "chicken-steak-desc": "大蒜酱汁。",
        "reimen": "特制冷面",
        "reimen-desc": "清爽的海鲜汤底。",
        "garlic-pizza": "蒜香肉酱披萨",
        "garlic-pizza-desc": "非常下酒。",
        "margherita": "玛格丽特披萨",
        "margherita-desc": "经典的番茄罗勒披萨。",
        "koumi-chahan": "香味炒饭",
        "koumi-chahan-desc": "充满大叶和姜的香气。",
        "mayu-chahan": "黑蒜油炒饭",
        "mayu-chahan-desc": "焦香蒜油，令人上瘾。",
        "taco-rice": "迷你塔可饭",
        "taco-rice-desc": "冲绳经典主食，迷你份量。",
        "vanilla-ice": "香草冰淇淋",
        "vanilla-ice-desc": "浓郁香草味。",
        "age-mochi": "炸年糕",
        "age-mochi-desc": "配黑糖浆和黄豆粉。",
        "beer": "生啤酒",
        "beer-desc": "Orion 生啤酒。",
        "awamori": "泡盛酒",
        "awamori-desc": "冲绳传统烈酒。",
        "sanpincha": "香片茶 (茉莉花茶)",
        "sanpincha-desc": "冲绳经典茶饮。"
    }
};

// ... (以下のallergenTranslations, foodMenuData, drinkMenuDataは変更なし、そのまま使ってください)
// 画像パスなどはご自身の環境のままでOKです
const allergenTranslations = {
    "jp": { "乳": "乳", "卵": "卵", "小麦": "小麦", "大豆": "大豆", "牛肉": "牛肉", "豚肉": "豚肉", "魚介": "魚介" },
    "en": { "乳": "Dairy", "卵": "Egg", "小麦": "Wheat", "大豆": "Soy", "牛肉": "Beef", "豚肉": "Pork", "魚介": "Seafood" },
    "cn": { "乳": "乳制品", "卵": "蛋", "小麦": "小麦", "大豆": "大豆", "牛肉": "牛肉", "豚肉": "猪肉", "魚介": "海鲜" }
};

const foodMenuData = [
    { category: "cat-otsumami", items: [
        { key: "iburigakko", price: "480円", allergens: ["乳"], img: "images/menu/iburigakko.jpg" },
        { key: "shutou-cheese", price: "480円", allergens: ["乳", "魚介"], img: "images/menu/shutou_cheese.jpg" },
        { key: "yamaimo-zakuzaku", price: "480円", allergens: [], img: "images/menu/yamaimo.jpg" },
        { key: "mozukusu", price: "480円", allergens: [], img: "images/menu/mozuku.jpg" },
        { key: "umibudou", price: "480円", allergens: [], img: "images/menu/umibudou.jpg" },
        { key: "kyuri-ippon", price: "480円", allergens: [], img: "images/menu/cucumber.jpg" },
        { key: "hiyayakko", price: "480円", allergens: ["大豆"], img: "images/menu/tofu.jpg" },
        { key: "caesar-salad", price: "540円", allergens: ["乳", "卵", "小麦"], img: "images/menu/salad.jpg" },
        { key: "pirikara-tamago", price: "480円", allergens: ["卵", "小麦", "大豆"], img: "images/menu/egg.jpg" },
        { key: "pirikara-menma", price: "480円", allergens: ["小麦", "大豆"], img: "images/menu/menma.jpg" },
        { key: "aburi-charshu", price: "620円", allergens: ["小麦", "大豆"], img: "images/menu/charshu.jpg" }
    ]},
    { category: "cat-agemono", items: [
        { key: "wakadori-karaage", price: "720円", allergens: ["小麦", "卵", "大豆"], img: "images/menu/karaage.jpg" },
        { key: "potato-fry", price: "640円", allergens: [], img: "images/menu/fries.jpg" },
        { key: "atsuage-yakumi", price: "620円", allergens: ["大豆"], img: "images/menu/atsuage.jpg" },
        { key: "youngcorn-tenpura", price: "640円", allergens: ["小麦", "卵"], img: "images/menu/corn.jpg" }
    ]},
    { category: "cat-ippinmono", items: [
        { key: "tacos-meatpie", price: "820円", allergens: ["小麦", "乳", "牛肉"], img: "images/menu/meatpie.jpg" },
        { key: "taimo-cheese", price: "580円", allergens: ["乳"], img: "images/menu/taimo.jpg" },
        { key: "mabo-dofu", price: "820円", allergens: ["大豆", "小麦", "豚肉"], img: "images/menu/mabo.jpg" },
        { key: "anchovy-cabbage", price: "640円", allergens: ["魚介"], img: "images/menu/cabbage.jpg" },
        { key: "gyoza", price: "640円", allergens: ["小麦", "大豆", "豚肉"], img: "images/menu/gyoza.jpg" },
        { key: "tofu-garlic", price: "640円", allergens: ["大豆"], img: "images/menu/tofu_garlic.jpg" },
        { key: "goya-chanpuru", price: "640円", allergens: ["卵", "大豆", "豚肉"], img: "images/menu/goya.jpg" },
        { key: "dashimaki", price: "560円", allergens: ["卵"], img: "images/menu/tamago.jpg" },
        { key: "niku-yakimochi", price: "560円", allergens: ["小麦", "大豆", "豚肉"], img: "images/menu/mochi.jpg" }
    ]},
    { category: "cat-niku", items: [
         { key: "gyu-rare-katsu", price: "1200円", allergens: ["小麦", "卵", "牛肉"], img: "images/menu/beef_katsu.jpg" },
         { key: "rib-steak", price: "1480円", allergens: ["牛肉"], img: "images/menu/steak.jpg" },
         { key: "wagyu-rib-steak", price: "2480円", allergens: ["牛肉"], img: "images/menu/wagyu.jpg" },
         { key: "hamburger", price: "980円", allergens: ["卵", "小麦", "乳", "牛肉", "豚肉"], img: "images/menu/burger.jpg" },
         { key: "chicken-tatsuta", price: "740円", allergens: ["小麦", "卵", "大豆"], img: "images/menu/chicken.jpg" },
         { key: "chicken-steak", price: "780円", allergens: ["小麦", "大豆"], img: "images/menu/chicken_steak.jpg" }
    ]},
    { category: "cat-main", items: [
        { key: "reimen", price: "820円", allergens: ["小麦", "卵"], img: "images/menu/noodles.jpg" },
        { key: "garlic-pizza", price: "720円", allergens: ["小麦", "乳", "豚肉"], img: "images/menu/pizza.jpg" },
        { key: "margherita", price: "720円", allergens: ["小麦", "乳"], img: "images/menu/margherita.jpg" },
        { key: "koumi-chahan", price: "780円", allergens: ["卵", "小麦", "大豆"], img: "images/menu/fried_rice.jpg" },
        { key: "mayu-chahan", price: "780円", allergens: ["卵", "小麦", "大豆"], img: "images/menu/mayu_rice.jpg" },
        { key: "taco-rice", price: "480円", allergens: ["乳", "牛肉"], img: "images/menu/taco_rice.jpg" }
    ]},
     { category: "cat-dessert", items: [
        { key: "vanilla-ice", price: "200円", allergens: ["乳", "卵"], img: "images/menu/ice_cream.jpg" },
        { key: "age-mochi", price: "300円", allergens: [], img: "images/menu/age_mochi.jpg" }
    ]}
];

const drinkMenuData = [
    { category: "cat-alcohol", items: [
        { key: "beer", price: "550円", allergens: ["小麦"], img: "images/menu/beer.jpg" },
        { key: "awamori", price: "500円", allergens: [], img: "images/menu/awamori.jpg" }
    ]},
     { category: "cat-nonalcohol", items: [
        { key: "sanpincha", price: "300円", allergens: [], img: "images/menu/tea.jpg" }
    ]}
];


