// 翻訳データ
const menuTranslations = {
    // =============================================================================
    // 日本語 (Japanese)
    // =============================================================================
    "jp": {
        // --- サイト全体 ---
        "catchphrase": "今夜も<br>かふーじゅに<br>集合。<br>アットホームな<br>酔い処",
        "sub-catchphrase": "旨い酒と肴、楽しいイベントで、<br>毎日が特別になる大衆居酒屋。",
        "about-title": "私たちの思い",
        "about-body-1": "「酔い処 かふーじゅ」の「かふーじゅ」とは、沖縄の言葉で「果報（かふう）」＝「幸せ、良い知らせ」を意味します。",
        "about-body-2": "私たちは、この小さな居酒屋が、訪れるお客様にとっての「幸せな場所」でありたいと願っています。<br>一度だけでなく、二度、三度と足を運びたくなるような、アットホームな空間づくり。<br>お一人お一人のお客様との出会いを大切にし、心を込めたおもてなしを。",
        "about-body-3": "そして、お店があるこの若狭という地域に根ざし、地域の皆様の笑顔と発展に、微力ながらも貢献していくこと。<br>それが「酔い処 かふーじゅ」の変わらぬ思いです。",
        "info-title": "店舗情報・アクセス",
        "menu-title": "お品書き",
        "events-title": "催し物",
        "contact-title": "ご予約・お問い合わせ",
        "contact-reserve-title": "ご予約について",
        "contact-reserve-desc": "ご予約は「お電話」または「InstagramのDM」にて承っております。<br>8名様以上のご予約（火曜日含む）は、1週間前までにご連絡をお願いいたします。",
        "contact-form-title": "お問い合わせフォーム",
        "form-name": "お名前",
        "form-email": "メールアドレス",
        "form-message": "お問い合わせ内容",
        "form-submit": "送信する",
        
        // --- イベント ---
        "event-1-title": "和牛ステーキ半額フェア",
        "event-1-date": "11月25日 (土) 18:00〜",
        "event-1-desc": "日頃の感謝を込めて、A5ランク和牛リブロースステーキ(2480円)を、なんと半額の1240円でご提供！数量限定、早い者勝ちです！",
        "event-2-title": "ビールDay",
        "event-2-desc": "生ビール何杯飲んでも1杯300円！",
        "event-3-title": "レディースDay",
        "event-3-desc": "女性グループ限定、デザート1品サービス！",
        "event-4-title": "肉の日",
        "event-4-desc": "対象の肉料理が全品10%OFF！",
        
        // --- カテゴリ ---
        "tab-food": "お料理 (Food)",
        "tab-drink": "お飲み物 (Drink)",
        "cat-otsumami": "おつまみ",
        "cat-agemono": "揚げ物",
        "cat-ippinmono": "一品もの",
        "cat-niku": "肉料理",
        "cat-main": "メイン",
        "cat-dessert": "デザート",
        "cat-alcohol": "アルコール",
        "cat-nonalcohol": "ノンアルコール",
        "modal-allergens-title": "アレルゲン",

        // --- メニューアイテム ---
        "iburigakko": "いぶりがっこチーズ",
        "iburigakko-desc": "燻製の香りとチーズのコク。",
        "shutou-cheese": "酒盗クリームチーズ",
        "shutou-cheese-desc": "日本酒泥棒。間違いない組み合わせ。",
        "yamaimo-zakuzaku": "山芋ザクザク",
        "yamaimo-zakuzaku-desc": "新鮮な山芋の食感をお楽しみください。",
        "mozukusu": "もずく酢",
        "mozukusu-desc": "沖縄定番のさっぱりおつまみ。",
        "umibudou": "海ぶどう",
        "umibudou-desc": "プチプチ食感がたまらない海の宝石。",
        "kyuri-ippon": "きゅうり一本漬け",
        "kyuri-ippon-desc": "とりあえずこれ。さっぱりと。",
        "hiyayakko": "冷や奴",
        "hiyayakko-desc": "シンプルイズベスト。",
        "caesar-salad": "シーザーサラダ",
        "caesar-salad-desc": "濃厚ドレッシングとクルトン。",
        "pirikara-tamago": "特製ピリ辛半熟玉子",
        "pirikara-tamago-desc": "とろーり半熟。特製のピリ辛ダレで。",
        "pirikara-menma": "ピリ辛おつまみメンマ",
        "pirikara-menma-desc": "ごま油香る、お酒が進むメンマ。",
        "aburi-charshu": "炙りチャーシュー",
        "aburi-charshu-desc": "香ばしく炙ったチャーシュー。",
        "wakadori-karaage": "若鶏からあげ",
        "wakadori-karaage-desc": "ジューシーな定番からあげ。",
        "potato-fry": "皮付きポテトフライ",
        "potato-fry-desc": "ホクホク。手が止まらない。",
        "atsuage-yakumi": "薬味たっぷり厚揚げ",
        "atsuage-yakumi-desc": "カリッと揚げた厚揚げ。",
        "youngcorn-tenpura": "ヤングコーン天ぷら",
        "youngcorn-tenpura-desc": "サクサク衣とコーンの甘み。",
        "tacos-meatpie": "タコスミートパイ",
        "tacos-meatpie-desc": "サクサクパイにスパイシーなタコスミート。",
        "taimo-cheese": "田芋チーズ焼き",
        "taimo-cheese-desc": "沖縄の田芋とチーズのハーモニー。",
        "mabo-dofu": "麻婆豆腐",
        "mabo-dofu-desc": "ピリッと本格派。",
        "anchovy-cabbage": "アンチョビキャベツ",
        "anchovy-cabbage-desc": "ニンニクとアンチョビ。",
        "gyoza": "餃子（5個）",
        "gyoza-desc": "パリッとジューシー。",
        "tofu-garlic": "豆腐ニンニク",
        "tofu-garlic-desc": "ガツンとニンニク。",
        "goya-chanpuru": "ゴーヤーチャンプルー",
        "goya-chanpuru-desc": "沖縄の魂。定番。",
        "dashimaki": "だし巻き卵",
        "dashimaki-desc": "ふわふわ。出汁が香る。",
        "niku-yakimochi": "肉焼きもち",
        "niku-yakimochi-desc": "甘辛い肉タレともちもち食感。",
        "gyu-rare-katsu": "牛レアカツ",
        "gyu-rare-katsu-desc": "サクッと衣、中はレア。",
        "rib-steak": "リブロースステーキ",
        "rib-steak-desc": "食べ応え抜群。",
        "wagyu-rib-steak": "和牛リブロースステーキ",
        "wagyu-rib-steak-desc": "特別な夜に。とろける旨味。",
        "hamburger": "特製ハンバーグ",
        "hamburger-desc": "肉汁たっぷり。",
        "chicken-tatsuta": "チキン竜田揚げ",
        "chicken-tatsuta-desc": "サクサク衣。",
        "chicken-steak": "チキンステーキ",
        "chicken-steak-desc": "皮はパリッと、身はジューシー。",
        "reimen": "かふーじゅ冷麺",
        "reimen-desc": "〆にぴったり。",
        "garlic-pizza": "ガーリックミートピザ",
        "garlic-pizza-desc": "ガツンとガーリック。",
        "margherita": "マルゲリータ",
        "margherita-desc": "定番ピザ。",
        "koumi-chahan": "香味チャーハン",
        "koumi-chahan-desc": "香味野菜が香る。",
        "mayu-chahan": "黒マー油チャーハン",
        "mayu-chahan-desc": "焦がしニンニク油。",
        "taco-rice": "〆のタコライス",
        "taco-rice-desc": "沖縄の〆といえば。",
        "vanilla-ice": "バニラアイス",
        "vanilla-ice-desc": "食後にさっぱり。",
        "age-mochi": "揚げ餅",
        "age-mochi-desc": "黒蜜きなこで。",
        "beer": "生ビール (ダミー)",
        "beer-desc": "キンキンに冷えてます。",
        "awamori": "泡盛 (ダミー)",
        "awamori-desc": "沖縄といえば。",
        "sanpincha": "さんぴん茶 (ダミー)",
        "sanpincha-desc": "沖縄の定番。"
    },

    // =============================================================================
    // 英語 (English)
    // =============================================================================
    "en": {
        "catchphrase": "Gather at<br>Kafuju.<br>A Cozy<br>Izakaya.",
        "sub-catchphrase": "Great sake, food, and fun events <br>make every day special.",
        "about-title": "Our Philosophy",
        "about-body-1": "'Kafuju' means 'good fortune' in Okinawan dialect.",
        "about-body-2": "We hope this small izakaya will be a happy place for all who visit.<br>We strive to create a welcoming, at-home atmosphere.",
        "about-body-3": "We aim to be rooted in this Wakasa community, contributing to the smiles and prosperity of the local area.",
        "info-title": "Info & Access",
        "menu-title": "Menu",
        "events-title": "Events",
        "contact-title": "Reservations",
        "contact-reserve-title": "Reservations",
        "contact-reserve-desc": "We accept reservations by Phone or Instagram DM.<br>For parties of 8 or more, please contact us at least one week in advance.",
        "contact-form-title": "Inquiry Form",
        "form-name": "Name",
        "form-email": "Email",
        "form-message": "Message",
        "form-submit": "Send",
        
        "event-1-title": "Wagyu Steak Half Price",
        "event-1-date": "Nov 25 (Sat) 18:00~",
        "event-1-desc": "A5 Wagyu Ribeye Steak half price! Limited quantity!",
        "event-2-title": "Beer Day",
        "event-2-desc": "Draft beer ¥300!",
        "event-3-title": "Ladies' Day",
        "event-3-desc": "Free dessert for ladies!",
        "event-4-title": "Meat Day",
        "event-4-desc": "Meat dishes 10% OFF!",
        
        "tab-food": "Food",
        "tab-drink": "Drink",
        "cat-otsumami": "Appetizers",
        "cat-agemono": "Fried Foods",
        "cat-ippinmono": "Side Dishes",
        "cat-niku": "Meat Dishes",
        "cat-main": "Rice & Noodles",
        "cat-dessert": "Dessert",
        "cat-alcohol": "Alcohol",
        "cat-nonalcohol": "Non-Alcoholic",
        "modal-allergens-title": "Allergens",

        "iburigakko": "Smoked Radish & Cheese",
        "iburigakko-desc": "Smoky aroma and rich cheese.",
        "shutou-cheese": "Shutou & Cream Cheese",
        "shutou-cheese-desc": "Bonito entrails. Best match for Sake.",
        "yamaimo-zakuzaku": "Crunchy Mountain Yam",
        "yamaimo-zakuzaku-desc": "Enjoy the fresh, crisp texture.",
        "mozukusu": "Mozuku Seaweed Vinegar",
        "mozukusu-desc": "Refreshing Okinawan seaweed.",
        "umibudou": "Sea Grapes",
        "umibudou-desc": "Sea jewels with a popping texture.",
        "kyuri-ippon": "Pickled Cucumber",
        "kyuri-ippon-desc": "A whole cucumber. Refreshing.",
        "hiyayakko": "Chilled Tofu",
        "hiyayakko-desc": "Simple tofu with ginger and onions.",
        "caesar-salad": "Caesar Salad",
        "caesar-salad-desc": "Rich dressing and croutons.",
        "pirikara-tamago": "Spicy Soft-boiled Egg",
        "pirikara-tamago-desc": "Marinated in special spicy sauce.",
        "pirikara-menma": "Spicy Bamboo Shoots",
        "pirikara-menma-desc": "Seasoned with sesame oil.",
        "aburi-charshu": "Seared Char Siu Pork",
        "aburi-charshu-desc": "Fragrant seared pork.",
        "wakadori-karaage": "Fried Chicken (Karaage)",
        "wakadori-karaage-desc": "Juicy Japanese fried chicken.",
        "potato-fry": "French Fries",
        "potato-fry-desc": "Crispy skin-on potato fries.",
        "atsuage-yakumi": "Fried Tofu with Toppings",
        "atsuage-yakumi-desc": "Crispy tofu with plenty of herbs.",
        "youngcorn-tenpura": "Baby Corn Tempura",
        "youngcorn-tenpura-desc": "Crispy batter and sweet corn.",
        "tacos-meatpie": "Taco Meat Pie",
        "tacos-meatpie-desc": "Crispy pie with spicy taco meat.",
        "taimo-cheese": "Baked Taro & Cheese",
        "taimo-cheese-desc": "Okinawan taro with melted cheese.",
        "mabo-dofu": "Mapo Tofu",
        "mabo-dofu-desc": "Authentic Sichuan style spicy tofu.",
        "anchovy-cabbage": "Anchovy Cabbage",
        "anchovy-cabbage-desc": "Garlic and anchovy flavor.",
        "gyoza": "Gyoza (5 pcs)",
        "gyoza-desc": "Crispy and juicy dumplings.",
        "tofu-garlic": "Garlic Tofu Stir-fry",
        "tofu-garlic-desc": "Garlic punch! Stamina booster.",
        "goya-chanpuru": "Goya Chanpuru",
        "goya-chanpuru-desc": "Okinawan bitter melon stir-fry.",
        "dashimaki": "Rolled Omelet",
        "dashimaki-desc": "Fluffy Japanese omelet with dashi.",
        "niku-yakimochi": "Pork-wrapped Mochi",
        "niku-yakimochi-desc": "Grilled rice cake with sweet soy sauce.",
        "gyu-rare-katsu": "Rare Beef Cutlet",
        "gyu-rare-katsu-desc": "Crispy outside, rare inside.",
        "rib-steak": "Ribeye Steak",
        "rib-steak-desc": "Hearty and flavorful.",
        "wagyu-rib-steak": "Wagyu Ribeye Steak",
        "wagyu-rib-steak-desc": "A5 Rank Wagyu. Melt-in-your-mouth.",
        "hamburger": "Hamburger Steak",
        "hamburger-desc": "Juicy patty with special sauce.",
        "chicken-tatsuta": "Chicken Tatsuta-age",
        "chicken-tatsuta-desc": "Crispy fried chicken.",
        "chicken-steak": "Chicken Steak",
        "chicken-steak-desc": "Crispy skin and juicy meat.",
        "reimen": "Cold Noodles",
        "reimen-desc": "Refreshing seafood broth soup.",
        "garlic-pizza": "Garlic Meat Pizza",
        "garlic-pizza-desc": "Great with beer.",
        "margherita": "Margherita Pizza",
        "margherita-desc": "Classic tomato and basil pizza.",
        "koumi-chahan": "Aromatic Fried Rice",
        "koumi-chahan-desc": "With ginger and green onions.",
        "mayu-chahan": "Black Garlic Fried Rice",
        "mayu-chahan-desc": "Rich burnt garlic oil flavor.",
        "taco-rice": "Mini Taco Rice",
        "taco-rice-desc": "Okinawan soul food. Mini size.",
        "vanilla-ice": "Vanilla Ice Cream",
        "vanilla-ice-desc": "Rich vanilla flavor.",
        "age-mochi": "Fried Mochi",
        "age-mochi-desc": "With brown sugar syrup.",
        "beer": "Draft Beer",
        "beer-desc": "Ice cold and refreshing.",
        "awamori": "Awamori",
        "awamori-desc": "Traditional Okinawan spirit.",
        "sanpincha": "Jasmine Tea",
        "sanpincha-desc": "Standard Okinawan tea."
    },

    // =============================================================================
    // 中国語 (Chinese - Simplified)
    // =============================================================================
    "cn": {
        "catchphrase": "今晚<br>来Kafuju<br>集合。<br>舒适的<br>居酒屋",
        "sub-catchphrase": "美味的酒和佳肴，有趣的活动，<br>让每天都变得特别。",
        "about-title": "我们的理念",
        "about-body-1": "“Kafuju”在冲绳方言中意为“好运”或“幸福”。",
        "about-body-2": "我们希望这家小小的居酒屋能成为所有来访顾客的“幸福之地”。<br>致力于营造温馨如家的氛围。",
        "about-body-3": "我们也希望能扎根于若狭社区，为当地居民的笑容尽一份力。",
        "info-title": "店铺信息",
        "menu-title": "菜单",
        "events-title": "活动",
        "contact-title": "预约 / 咨询",
        "contact-reserve-title": "关于预约",
        "contact-reserve-desc": "接受电话或Instagram私信预约。<br>8人以上团体请提前一周联系。",
        "contact-form-title": "咨询表",
        "form-name": "姓名",
        "form-email": "邮箱",
        "form-message": "内容",
        "form-submit": "发送",
        
        "event-1-title": "和牛牛排半价",
        "event-1-date": "11月25日 (周六) 18:00〜",
        "event-1-desc": "A5级和牛肋眼牛排半价优惠！数量有限！",
        "event-2-title": "周一<br>啤酒日",
        "event-2-desc": "生啤酒每杯300日元！",
        "event-3-title": "周三<br>女士日",
        "event-3-desc": "女性团体赠送甜点！",
        "event-4-title": "29日<br>肉之日",
        "event-4-desc": "肉类菜品9折优惠！",
        
        "tab-food": "料理 (Food)",
        "tab-drink": "饮料 (Drink)",
        "cat-otsumami": "前菜",
        "cat-agemono": "炸物",
        "cat-ippinmono": "一品料理",
        "cat-niku": "肉类料理",
        "cat-main": "主食",
        "cat-dessert": "甜点",
        "cat-alcohol": "酒类",
        "cat-nonalcohol": "无酒精",
        "modal-allergens-title": "过敏原",

        "iburigakko": "烟熏萝卜奶酪",
        "iburigakko-desc": "烟熏香气与浓郁奶酪。",
        "shutou-cheese": "酒盗奶油芝士",
        "shutou-cheese-desc": "腌制鲣鱼内脏。清酒绝配。",
        "yamaimo-zakuzaku": "香脆山药",
        "yamaimo-zakuzaku-desc": "口感清脆的新鲜山药。",
        "mozukusu": "醋拌水云",
        "mozukusu-desc": "冲绳特产海藻。",
        "umibudou": "海葡萄",
        "umibudou-desc": "口感独特的“绿色鱼子酱”。",
        "kyuri-ippon": "腌黄瓜",
        "kyuri-ippon-desc": "清爽可口。",
        "hiyayakko": "日式冷豆腐",
        "hiyayakko-desc": "简单的美味，配姜末葱花。",
        "caesar-salad": "凯撒沙拉",
        "caesar-salad-desc": "浓郁酱汁配面包丁。",
        "pirikara-tamago": "特制香辣半熟蛋",
        "pirikara-tamago-desc": "腌制在特制辣酱中。",
        "pirikara-menma": "香辣笋干",
        "pirikara-menma-desc": "芝麻油风味。",
        "aburi-charshu": "炙烤叉烧",
        "aburi-charshu-desc": "香喷喷的烤猪肉。",
        "wakadori-karaage": "日式炸鸡块",
        "wakadori-karaage-desc": "鲜嫩多汁的经典炸鸡。",
        "potato-fry": "带皮炸薯条",
        "potato-fry-desc": "热腾腾的美味。",
        "atsuage-yakumi": "佐料满满炸豆腐",
        "atsuage-yakumi-desc": "外酥里嫩，配大量佐料。",
        "youngcorn-tenpura": "玉米笋天妇罗",
        "youngcorn-tenpura-desc": "酥脆面衣和玉米的甜味。",
        "tacos-meatpie": "塔可肉派",
        "tacos-meatpie-desc": "酥皮配香辣塔可肉酱。",
        "taimo-cheese": "焗烤田芋芝士",
        "taimo-cheese-desc": "冲绳田芋与芝士的完美结合。",
        "mabo-dofu": "麻婆豆腐",
        "mabo-dofu-desc": "正宗四川风味。",
        "anchovy-cabbage": "凤尾鱼炒卷心菜",
        "anchovy-cabbage-desc": "大蒜和凤尾鱼的咸香。",
        "gyoza": "煎饺",
        "gyoza-desc": "皮脆馅大，肉汁丰富。",
        "tofu-garlic": "大蒜炒豆腐",
        "tofu-garlic-desc": "蒜香浓郁，补充体力。",
        "goya-chanpuru": "苦瓜炒什锦",
        "goya-chanpuru-desc": "冲绳的灵魂料理。",
        "dashimaki": "高汤鸡蛋卷",
        "dashimaki-desc": "口感松软，充满高汤香气。",
        "niku-yakimochi": "肉卷烤年糕",
        "niku-yakimochi-desc": "甜咸酱汁配Q弹年糕。",
        "gyu-rare-katsu": "炸半熟牛排",
        "gyu-rare-katsu-desc": "外酥里嫩的半熟口感。",
        "rib-steak": "肋眼牛排",
        "rib-steak-desc": "分量十足，肉香四溢。",
        "wagyu-rib-steak": "和牛肋眼牛排",
        "wagyu-rib-steak-desc": "A5等级和牛，入口即化。",
        "hamburger": "特制汉堡肉饼",
        "hamburger-desc": "肉汁饱满，配特制酱汁。",
        "chicken-tatsuta": "龙田风炸鸡",
        "chicken-tatsuta-desc": "酥脆面衣。",
        "chicken-steak": "香煎鸡排",
        "chicken-steak-desc": "皮脆肉嫩。",
        "reimen": "特制冷面",
        "reimen-desc": "清爽的海鲜汤底。",
        "garlic-pizza": "蒜香肉酱披萨",
        "garlic-pizza-desc": "浓郁蒜香，非常下酒。",
        "margherita": "玛格丽特披萨",
        "margherita-desc": "经典的番茄罗勒披萨。",
        "koumi-chahan": "香味炒饭",
        "koumi-chahan-desc": "充满蔬菜香气。",
        "mayu-chahan": "黑蒜油炒饭",
        "mayu-chahan-desc": "焦香蒜油，令人上瘾。",
        "taco-rice": "迷你塔可饭",
        "taco-rice-desc": "冲绳经典主食，迷你份量。",
        "vanilla-ice": "香草冰淇淋",
        "vanilla-ice-desc": "餐后甜点。",
        "age-mochi": "炸年糕",
        "age-mochi-desc": "配黑糖浆和黄豆粉。",
        "beer": "生啤酒",
        "beer-desc": "冰镇爽口。",
        "awamori": "泡盛酒",
        "awamori-desc": "冲绳传统烈酒。",
        "sanpincha": "香片茶 (茉莉花茶)",
        "sanpincha-desc": "冲绳经典茶饮。"
    }
};

const allergenTranslations = {
    "jp": { "乳": "乳", "卵": "卵", "小麦": "小麦", "大豆": "大豆", "牛肉": "牛肉", "豚肉": "豚肉", "魚介": "魚介" },
    "en": { "乳": "Dairy", "卵": "Egg", "小麦": "Wheat", "大豆": "Soy", "牛肉": "Beef", "豚肉": "Pork", "魚介": "Seafood" },
    "cn": { "乳": "乳制品", "卵": "蛋", "小麦": "小麦", "大豆": "大豆", "牛肉": "牛肉", "豚肉": "猪肉", "魚介": "海鲜" }
};

// メニューデータ
const foodMenuData = [
    { category: "cat-otsumami", items: [
        { key: "iburigakko", price: "480円", allergens: ["乳"], img: "images/menu/iburigakko.jpg" },
        { key: "shutou-cheese", price: "480円", allergens: ["乳", "魚介"], img: "images/menu/shutou_cheese.jpg" },
        { key: "yamaimo-zakuzaku", price: "480円", allergens: [], img: "images/menu/yamaimo.jpg" },
        { key: "mozukusu", price: "480円", allergens: [], img: "images/menu/mozuku.jpg" },
        { key: "umibudou", price: "480円", allergens: [], img: "images/menu/umibudou.jpg" },
        { key: "kyuri-ippon", price: "480円", allergens: [], img: "images/menu/cucumber.jpg" },
        { key: "hiyayakko", price: "480円", allergens: ["大豆"], img: "images/menu/tofu.jpg" },
        { key: "caesar-salad", price: "540円", allergens: ["乳", "卵", "小麦"], img: "images/menu/salad.jpg" },
        { key: "pirikara-tamago", price: "480円", allergens: ["卵", "小麦", "大豆"], img: "images/menu/egg.jpg" },
        { key: "pirikara-menma", price: "480円", allergens: ["小麦", "大豆"], img: "images/menu/menma.jpg" },
        { key: "aburi-charshu", price: "620円", allergens: ["小麦", "大豆"], img: "images/menu/charshu.jpg" }
    ]},
    { category: "cat-agemono", items: [
        { key: "wakadori-karaage", price: "720円", allergens: ["小麦", "卵", "大豆"], img: "images/menu/karaage.jpg" },
        { key: "potato-fry", price: "640円", allergens: [], img: "images/menu/fries.jpg" },
        { key: "atsuage-yakumi", price: "620円", allergens: ["大豆"], img: "images/menu/atsuage.jpg" },
        { key: "youngcorn-tenpura", price: "640円", allergens: ["小麦", "卵"], img: "images/menu/corn.jpg" }
    ]},
    { category: "cat-ippinmono", items: [
        { key: "tacos-meatpie", price: "820円", allergens: ["小麦", "乳", "牛肉"], img: "images/menu/meatpie.jpg" },
        { key: "taimo-cheese", price: "580円", allergens: ["乳"], img: "images/menu/taimo.jpg" },
        { key: "mabo-dofu", price: "820円", allergens: ["大豆", "小麦", "豚肉"], img: "images/menu/mabo.jpg" },
        { key: "anchovy-cabbage", price: "640円", allergens: ["魚介"], img: "images/menu/cabbage.jpg" },
        { key: "gyoza", price: "640円", allergens: ["小麦", "大豆", "豚肉"], img: "images/menu/gyoza.jpg" },
        { key: "tofu-garlic", price: "640円", allergens: ["大豆"], img: "images/menu/tofu_garlic.jpg" },
        { key: "goya-chanpuru", price: "640円", allergens: ["卵", "大豆", "豚肉"], img: "images/menu/goya.jpg" },
        { key: "dashimaki", price: "560円", allergens: ["卵"], img: "images/menu/tamago.jpg" },
        { key: "niku-yakimochi", price: "560円", allergens: ["小麦", "大豆", "豚肉"], img: "images/menu/mochi.jpg" }
    ]},
    { category: "cat-niku", items: [
         { key: "gyu-rare-katsu", price: "1200円", allergens: ["小麦", "卵", "牛肉"], img: "images/menu/beef_katsu.jpg" },
         { key: "rib-steak", price: "1480円", allergens: ["牛肉"], img: "images/menu/steak.jpg" },
         { key: "wagyu-rib-steak", price: "2480円", allergens: ["牛肉"], img: "images/menu/wagyu.jpg" },
         { key: "hamburger", price: "980円", allergens: ["卵", "小麦", "乳", "牛肉", "豚肉"], img: "images/menu/burger.jpg" },
         { key: "chicken-tatsuta", price: "740円", allergens: ["小麦", "卵", "大豆"], img: "images/menu/chicken.jpg" },
         { key: "chicken-steak", price: "780円", allergens: ["小麦", "大豆"], img: "images/menu/chicken_steak.jpg" }
    ]},
    { category: "cat-main", items: [
        { key: "reimen", price: "820円", allergens: ["小麦", "卵"], img: "images/menu/noodles.jpg" },
        { key: "garlic-pizza", price: "720円", allergens: ["小麦", "乳", "豚肉"], img: "images/menu/pizza.jpg" },
        { key: "margherita", price: "720円", allergens: ["小麦", "乳"], img: "images/menu/margherita.jpg" },
        { key: "koumi-chahan", price: "780円", allergens: ["卵", "小麦", "大豆"], img: "images/menu/fried_rice.jpg" },
        { key: "mayu-chahan", price: "780円", allergens: ["卵", "小麦", "大豆"], img: "images/menu/mayu_rice.jpg" },
        { key: "taco-rice", price: "480円", allergens: ["乳", "牛肉"], img: "images/menu/taco_rice.jpg" }
    ]},
     { category: "cat-dessert", items: [
        { key: "vanilla-ice", price: "200円", allergens: ["乳", "卵"], img: "images/menu/ice_cream.jpg" },
        { key: "age-mochi", price: "300円", allergens: [], img: "images/menu/age_mochi.jpg" }
    ]}
];

const drinkMenuData = [
    { category: "cat-alcohol", items: [
        { key: "beer", price: "550円", allergens: ["小麦"], img: "images/menu/beer.jpg" },
        { key: "awamori", price: "500円", allergens: [], img: "images/menu/awamori.jpg" }
    ]},
     { category: "cat-nonalcohol", items: [
        { key: "sanpincha", price: "300円", allergens: [], img: "images/menu/tea.jpg" }
    ]}
];


